SET(CMAKE_SYSTEM_NAME     Linux)
SET(CMAKE_SYSTEM_PROCESSOR armv7l)
SET(CMAKE_SYSTEM_VERSION 1)
SET(CMAKE_CROSSCOMPILING TRUE)
SET(BUILD_TOOL_ROOT_PATH "D:/toolchains/gcc-linaro-7.5.0-2019.12-i686-mingw32_arm-linux-gnueabihf" )
SET(sysroot_target  "D:/toolchains/gcc-linaro-7.5.0-2019.12-i686-mingw32_arm-linux-gnueabihf/arm-linux-gnueabihf/libc" )
SET(tools           "D:/toolchains/gcc-linaro-7.5.0-2019.12-i686-mingw32_arm-linux-gnueabihf/bin" )

SET(CMAKE_C_COMPILER    "D:/toolchains/gcc-linaro-7.5.0-2019.12-i686-mingw32_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc.exe" )
SET(CMAKE_CXX_COMPILER  "D:/toolchains/gcc-linaro-7.5.0-2019.12-i686-mingw32_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++.exe" )
SET(CMAKE_LIBRARY_ARCHITECTURE arm-linux-gnueabihf)
SET(CMAKE_SYSROOT   "D:/toolchains/gcc-linaro-7.5.0-2019.12-i686-mingw32_arm-linux-gnueabihf/arm-linux-gnueabihf/libc" )
SET(CMAKE_SKIP_BUILD_RPATH TRUE)
SET(CMAKE_USE_EXTERNAL_RPATH_FOR_INSTALL TRUE)
SET(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY" )
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
